### PR TITLE
refactor JsonLdOptions to take document loader factory instead of loader

### PR DESCRIPTION
**Pull request by damooo**
Addresses #143

### CODE REVIEW

**Comment by pchampin** [comment]
thanks a lot @damooo .

A few questions:

* is the `LoaderFactory` trait really needed? Could we not simply make `JsonLdOptions` generic over `<LF: Fn() -> L, L: Loader<...>> ` ?? I realize that it may have usability problems, but did you consider it?

* if `LoaderFactory` is a better option, then do we really need the two specific implementations (`DefaultLoaderFactory` and `ClosureLoaderFactory`) of this type? I would rather have a blanket implementation of `LoaderFactory` for all `F: Fn() -> L where L: Loader<...>`, so that any closure/function returning a loader would implement it. Note that `MyLoader::default` would also fall into that category.

**Comment by pchampin** [comment]
all this makes a lot of sense, you convinced me :)

May I suggest, however, to change the signature of `with_loader_factory` to expend a closure/function rather than a full-fledged LoaderFactory? The methodwould wrap it in a `ClosureLoaderFactory` internally. This would improve the usability of the method, IMO.

(and people could still pass SomeLoader::default if they want -- it does not really matter at this point whether we use `ClosureLoaderFactory` or `DefaultLoaderFactory` in this case)

**Comment by damooo** [comment]
> (and people could still pass SomeLoader::default if they want -- it does not really matter at this point whether we use ClosureLoaderFactory or DefaultLoaderFactory in this case)

They are not the only ones? For example i will be using a *named* struct called `CloningLoaderFactory`, that have to be instantiated with a template loader, which will be cloned onwards. Then we cannot supply this factory instance?

Could we have a seperate method instead?

Also, it may be useful if we also provide named struct `CloningLoaderFactory` also by default, which covers most of the cases, so that users can name it in field types if needed.

**Comment by pchampin** [comment]
> For example i will be using a _named_ struct called `CloningLoaderFactory`, that have to be instantiated with a template loader, which will be cloned onwards. Then we cannot supply this factory instance?

You could still pass the following closure:
```rust
move || templateLoader.clone()
```
and get exactly the same result, couldn't you?

**Comment by damooo** [comment]
Yes, but what if we want to "name" the concrete type for generic? for type of a field in a struct?

For example, a struct, that includes parser field in it like following:

```rust
struct SomeConfig {
    jsonld_parser: JsonLdParser<CloningLoaderFactory<CachingHttpLoader>>,
   a: String,
   b: u32,
}
```

We cannot name the type of `jsonld_parser` field in the struct, as closure's type cannot be named.

**Comment by pchampin** [comment]
> If we use `ClosureLoaderFactory`, we cannot name the type of `jsonld_parser` field in the struct, as closure's type is anonymous, and cannot be named.

That's right, you convinced again :)

**Comment by pchampin** [comment]
I have rebased your PR (77600a2) and made a few additions (436e0e8, 54a84e6, e2d3df6), so this PR is essentially merged, even though GitHub does not recognized it. Thanks again for your work.

**Comment by damooo** [comment]
_/\\\_

**Pull request closed without merging**
