### PR TITLE
Introduce TermError

### PR DESCRIPTION
**Pull request by MattesWhite**
This PR starts the process of gradually removing `error-chain` from `sophia` as suggested in #8.

It starts by moving errors related to the creation of terms to an own `sophia::term::TermError`.

Temporary, a `impl From<TermError> for Error` was done in order to not have to refactor `ParserError` as well.

---

BTW @pchampin great work removing the lifetimes 👍

### CODE REVIEW

**Comment by pchampin** [comment]
Great PR :+1: , but... bad timing :-/ I was myself working on the parser module, which created some conflicts...

This should not be to hard to fix, though, since
* `nt.rs` is now the old `rio_nt.rs`, which you didn't touch
* `rio_common.rs` is now calling the unchecked constructors (Rio does the checking) so no TermError handling is required there anymore.

**Comment by pchampin** [comment]
Looking good!
For keeping the history clean, would you mind submitting a new PR rebased on top of master, either with `rebase -i` or maybe just a single commit with all your changes (they are focused enough)... Sorry for the trouble...

**Comment by MattesWhite** [comment]
As far as I know you can select to [squash and merge](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request#merging-a-pull-request-on-github) a PR which squashes all commits of the PR into a single one. 

Further reading:

- [Squash and Merge](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits)

**Comment by pchampin** [comment]
Good idea. I am not sure how/if it works when the PR has intermediate merges, but it's worth a try.

**Pull request merged**
